language: R
sudo: false
cache: packages
warnings_are_errors: true
after_success:
  - Rscript -e 'covr::coveralls()'

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qd6zm8h/hJk97ParcyV0cGgRu0K3AoUwkF2G9cUmc4npDF2KJFsb3wLaSi14EO91M1MHDVg6zwLwJ3iPmOpY8Ni+R94lyXDJ/rd58k9uAtAnzbkPK6ej5xDAe/+GJUhl9FyGEn4NK4jrOtJSP684KZRHmA848pP90Jdi2iG24eCGvozJcwTl+0meGwD9uzgO//CvBMw3vVfCx1ers3zzTYcMLNMX2ms+utWhn5rZMfqSdOFSa9W6WLueNiGjzhPj1nIwOdhRrYDMNTtm8CiHZlWS5R/4QVBaSl9keF6tcGfBAnKvk+mcQXFOY4J1Eif60aUu/yYOrYqyerdn2mXUfvYk7uJvN7sZ2rifvpdpy6h39Z9JpoA7iHWaYAWfefLg9ytYEdhdfYO964jlhRsvIlZTfEzDUxcofjT0CexWWMkc/hTavrz1RwR3Zda6D0nFOqHE6dXkwfMkRcLbMlSZFEdwV6jVelkHwMAKUGc9vAX3sPTj/0zjVmYPhKiix+xCFFNNkSAbPOiXV3kYQAt/OWDnC2I+ReBsDvtTJ/PUQRYwYBaII2CrMMrxFvpJQ1I4TRQN0InQVNDNln4Pog7936a0yO91zjQCN1IZSq4UzLe92rKPfRhKXw7myMxUSxoxk/MW4L3J18qrB0lQjyJdhrlrD3S2Rn5V5OMlVIN6bY0=
  file: I2C2*.t*gz
  on:
    repo: muschellij2/I2C2
